plugins:
  subscription_client_enabled:
    default: true
    client: true
  subscription_client_verbose_logs:
    default: false
  subscription_client_warning_notices_on_dashboard:
    default: true
  subscription_client_allow_moderator_subscription_management:
    default: false
  subscription_client_allow_moderator_supplier_authorization:
    default: false
    client: true
  subscription_client_request_plugin_statuses:
    default: false
    hidden: true
