plugins:
  subscription_client_enabled:
    default: true
    client: true
  subscription_client_verbose_logs:
    default: false
  subscription_client_critical_notices_on_dashboard:
    default: true
    client: true
