name: Linting

on:
  push:
    branches:
      - master
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Setup bundler
        run: gem install bundler -v 2.1.4 --no-doc

      - name: Setup gems
        run: bundle install --jobs 4

      - name: Rubocop
        run: bundle exec rubocop .
